version: '3'
services:
  app:
    build: .
    ports:
      - "6000:6000"
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: flask_task_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
